#:schema {{schema_filepath}}
# This toml holds the workspace's metadata

id = "workspace_id_here"
name = "workspace_name_here"
type = "workspace_type_here" # Allowed_values: {{allowed_workspace_types}}