# NOTE: This will be running in project root
site_name: OpenViatica Documentation
docs_dir: ./
theme:
  name: material
  palette:
    scheme: slate
plugins:
  - search
  - same-dir
  - drawio:
      toolbar: true      # Shows the zoom/fullscreen toolbar on hover
      viewer_js: "https://viewer.diagrams.net/js/viewer-static.min.js"
      darkmode: true
      edit: false
  - exclude:
      glob:
        - ".venv/*"
        - ".venv-dev/*"
        - ".vscode/*"
        - "OpenViatica.egg-info/*"
        - "Project_Source/Code/*"
        - "Project_Source/Dev_Tools/*"
        - "Project_Source/Validation_Code/*"
        - "Project_Source/README.md"

nav:
  - Home: README.md 
  
  - Documentation: 
    - Overview: Project_Source/Documentation/README.md
    - Code_Documentation: Project_Source/Documentation/Code_Documentation/README.md
    - Contribution_Documentation: Project_Source/Documentation/Contribution_Documentation/README.md
    - Project_Documentation: Project_Source/Documentation/Project_Documentation/README.md
    - Usage_Documentation: Project_Source/Documentation/Usage_Documentation/README.md

# Add this section at the bottom (root level)
extra_css:
  - Project_Source/mkdocs/extra.css