[project]
name="OpenViatica"
version="0.0.1"
dependencies = []

# ----------------------------
# Developer Environment
# ----------------------------
[tool.hatch.envs.dev]
dependencies = [
    # Hatch and uv are assumed as part of the setup.py

    # Type checkers
    "mypy", # Static Typechecker, will be using mypy --strict
    "pydantic", # For data typechecker
    "typeguard", # For function parameters typechecker

    # Documentation dependencies
    "mkdocs-material",
    "watchdog",
    "mkdocs-build-plantuml-plugin"
]
installer = "uv"
uv-compile = true
path = ".venv-dev"  # dev environment inside project folder



# ----------------------------
# Default Environment (runtime)
# ----------------------------
[tool.hatch.envs.default]
type = "virtual"
path = ".venv"  
installer = "uv"
uv-compile = true

