[project]
name="OpenViatica"
version="0.1"
dependencies = []
authors = [{name = "ftorres7382"}]
maintainers = [{name = "ftorres7382"}]

# ----------------------------
# Developer Environment
# ----------------------------
[tool.hatch.envs.dev]
type = "virtual"
dependencies = [
    # Hatch and uv are assumed as part of the setup.py

    # Type checkers
    "mypy", # Static Typechecker, will be using mypy --strict
    "pydantic", # For data typechecker
    "typeguard", # For function parameters typechecker

    # Documentation dependencies
    "mkdocs-material",
    "mkdocs-drawio",
    "mkdocs-same-dir",
    "mkdocs-exclude",
]
installer = "uv"
uv-compile = true
path = ".venv-dev"  # dev environment inside project folder

# Shorten Bash path
env-vars = { PROMPT_DIRTRIM = "1" }



# ----------------------------
# Default Environment (runtime)
# ----------------------------
[tool.hatch.envs.default]
type = "virtual"
path = ".venv"  
installer = "uv"
uv-compile = true


