[project]
name="OpenViatica"
version="0.1"
dependencies = [
    "pydantic", # For data typechecker
    "typeguard", # For function parameters typechecker
]
authors = [{name = "ftorres7382"}]
maintainers = [{name = "ftorres7382"}]
requires-python = ">=3.12"
license = {file = "LICENSE"}

[dependency-groups]
dev = [
    # Type checkers
    "pytest",
    "mypy", # Static Typechecker, will be using mypy --strict

    # Rust dependencies
    "maturin"
]

docs = [
  "mkdocs-material",
  "mkdocs-drawio",
  "mkdocs-same-dir",
  "mkdocs-exclude",
]

# DO THE LICENSE HEADERS
extra = [
    "licenseheaders"
]

# Set both dev and docs as the default
[tool.uv]
package = true
default-groups = ["dev", "docs", "extra"]
# Rebuild the package if any of these files change
cache-keys = [
    { file = "pyproject.toml" },
]


[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
# This handles what Hatch used to do. It looks in 'python/' 
# and finds the 'OpenViatica' folder automatically.
python-source = "python"
# The Rust module will be accessible as OpenViatica._rust
module-name = "OpenViatica._OpenViatica_rs"


[tool.pytest.ini_options]
# Always look in the tests directory
testpaths = ["tests"]
# Add helpful flags (v = verbose, ra = show extra summary info)
addopts = "-v -ra"
# Ensure the src folder is in the path for testing
pythonpath = ["python"]

[tool.mypy]
strict = true
# Mypy also needs to know where to look
mypy_path = "python"