# NOTE: The type hints can asolutely be out of date.
#       If they are out of date, please notify it so it gets corrected.

[app_database]
engine = "sqlite" # t.Literal["sqlite", "postgres"]
database_name = "OpenViatica_App"

    [app_database.sqlite]
    path = "./app/Data/" # str

    [app_database.postgres]
    host = "localhost" # str
    user = "admin" # str
    # Passwoer should probably be stored somewhere else, but idk where
