# NOTE: The type hints can asolutely be out of date.
#       If they are out of date, please notify it so it gets corrected.

[app_database]
engine = "sqlite" # t.Literal["sqlite", "postgres"]

    [app_database.sqlite]
    # str
    path = "./config/Data/internal.db" # str

    [app_database.postgres]
    host = "localhost" # str
    user = "admin" # str
