# NOTE: The type hints can asolutely be out of date.
#       If they are out of date, please notify it so it gets corrected.

mode = ""

[app_database]
engine = "sqlite" # t.Literal["sqlite", "postgres"]
database_name = "OpenViatica_App"

    [app_database.sqlite]
    path = "./app/Data/" # str

    [app_database.postgres]
    host = "localhost" # str
    user = "admin" # str

# This is the default settings for any workspace that is created
[workspace_settings]
template_workspace_folder_path = "app/Workspace_Files/Template_Workspace"

# Paths that would be relevant to the workspace itself
user_workspace_foldername = "Work"
internal_system_foldername = "System"
sytem_config_foldername = "Config"
setup_script_relpath = "setup_workspace/setup.py"


# Settings for where the workspaces should be hosted
base_folder_path = "Workspaces/"
admin_workspace_name = "Admin_Workspace"

