dependencies = [
    "openviatica",
    "ipykernel",
    "numpy",
    "pandas",
    "openpyxl",
    "polars",
    "duckdb",
    "matplotlib",
    "plotly",
    "dash",
    "seaborn",
    "mkdocs",
    "mkdocs-material",
    "flask",
    "fastapi"
]